name: WakaTime Readme
on:
  schedule:
    - cron: '0 * * * *' # 毎時
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: last_7_days
          SHOW_TITLE: true
          SHOW_TOTAL: true
          SHOW_TIME: true
          SHOW_MASKED_TIME: false
          LANG_COUNT: 5
          COMMIT_MESSAGE: 'chore(readme): update wakatime stats'
